const IMAGE = {
    ICON_HOME_BLACK: require('../images/home-back.png'),
    ICON_HOME: require('../images/home.png'),
    ICON_COFFEE: require('../images/pngguru.com.png'),
    ICON_FOOD: require('../images/food.png'),
    ICON_BEVERAGE: require('../images/beverage.png'),
    ICON_TEA: require('../images/tea.png'),
    ICON_LATE: require('../images/late2.png'),
    ICON_ICECOFFEE: require('../images/Icecoffee.png'),
    ICON_AMERICANO: require('../images/Americano.png'),
    ICON_ROOF: require('../images/roof.png'),
    ICON_COFEESHOP: require('../images/cofeeshop.png'),
    ICON_INTRACT: require('../images/integrate.png'),
    ICON_INTEGRETE: require('../images/companies.png'),
    ICON_INVESTMENT: require('../images/money2.png'),
    ICON_INVOLVE: require('../images/customer_relations.png'),
    ICON_LOG: require('../images/login.png'),
    ICON_LOGO2: require('../images/logo.png'),
    ICON_LOGO_DARK: require('../images/darkLogo.png'),
    ICON_SLIDE1: require('../images/slide1.jpg'),
    ICON_SLIDE2: require('../images/slide2.png'),
    ICON_SLIDE3: require('../images/slide3.jpg'),
    ICON_SLIDE4: require('../images/slide4.png'),
    ICON_SLIDE5: require('../images/slide5.jpg'),
    ICON_SLIDE6: require('../images/slide6.jpg'),
    ICON_SLIDE7: require('../images/slide7.png'),
    ICON_PROFILE: require('../images/profiled.png'),
    ICON_FAVOURITE1: require('../images/favorits1.jpg'),
    ICON_FAVOURITE2: require('../images/favourits2.jpg'),
    ICON_MALOGO: require('../images/marlenlogo.png'),
    ICON_WHEREHOUSE: require('../images/Group51.png'),
    ICON_ICONS: require('../images/icons.jpg'),
    ICON_SMILECOFFEE: require('../images/smileCoffee.png'),
    ICON_LEAF: require('../images/leaf.png'),
    ICON_COFFEE: require('../images/cup.png'),
    ICON_POLYGON: require('../images/Polygon.png'),
    ICON_HOUSE: require('../images/house.png'),
    ICON_ABTIMG1: require('../images/abtimg1.jpg'),
    ICON_ABTIMG2: require('../images/abtimg2.jpg'),
    ICON_ABTIMG3: require('../images/abtimg3.jpg'),
    ICON_ABTIMG4: require('../images/abtimg4.jpg'),
    ICON_ABTIMG6: require('../images/muffin.png'),
    ICON_NO_INTERNET: require('../images/noInte.png'),

}

export { IMAGE }